# Generated by Django 2.2.18 on 2021-09-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_categories_to_fetch', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('signature_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriorHealthPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=100)),
                ('health_plan_name', models.CharField(max_length=20)),
                ('your_name', models.CharField(blank=True, max_length=100)),
                ('member_id', models.CharField(max_length=10)),
                ('subscriber_id', models.CharField(max_length=10)),
                ('group_id', models.CharField(max_length=10)),
                ('plan_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
