# Generated by Django 2.2.18 on 2021-09-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0002_auto_20210902_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsentDate',
            new_name='ConsentDateModel',
        ),
        migrations.RenameModel(
            old_name='PriorHealthPlan',
            new_name='PriorHealthPlanModel',
        ),
    ]
