# Generated by Django 2.2.18 on 2021-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0004_consentdatemodel_signature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
