# Generated by Django 2.2.18 on 2021-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0005_auto_20210903_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentdatemodel',
            name='data_categories_to_fetch',
            field=models.CharField(choices=[('everything', 'Everything'), ('only non-sensitive data', 'Only Non-Sensitive Data')], max_length=100),
        ),
    ]
